
import { Avatar, AvatarImage } from "@/components/ui/avatar";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  CardFooter
} from "@/components/ui/card";
import {
  Briefcase,
  Target,
  Rocket,
  Lightbulb,
  Cpu,
  BarChart,
  BookOpen,
  Newspaper,
  History,
  CheckCircle,
  TrendingUp,
  TrendingDown,
  Scale,
  ArrowRight
} from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import DashboardLayout from "@/components/dashboard/dashboard-layout";

const teamMembers = [
  {
    name: "Shiv Rastogi",
    role: "CEO",
    avatar: "https://picsum.photos/seed/shiv/200",
    aiHint: "man portrait",
  },
  {
    name: "Nakul Limbani",
    role: "Co-Founder",
    avatar: "https://picsum.photos/seed/nakul/200",
    aiHint: "man portrait",
  },
  {
    name: "Prakeerth Gollapati",
    role: "CTO",
    avatar: "https://picsum.photos/seed/prakeerth/200",
    aiHint: "man portrait",
  },
];

const features = [
  {
    icon: BarChart,
    title: "Strategy Backtesting",
    description: "Test your trading ideas against historical data to see how they would have performed, with AI-driven suggestions for improvement.",
    link: "/backtesting"
  },
  {
    icon: BookOpen,
    title: "Paper Trading",
    description: "Practice trading with virtual funds in a risk-free, simulated market environment to hone your skills.",
    link: "/paper-trading"
  },
  {
    icon: Newspaper,
    title: "Sentiment Analysis",
    description: "Gauge market mood by analyzing news headlines and social media sentiment for various stocks.",
    link: "/sentiment"
  },
  {
    icon: Cpu,
    title: "AI-Driven Signals",
    description: "Receive actionable buy, sell, or hold signals generated by our advanced AI models, with explanations for every decision.",
    link: "/ai-signals"
  },
  {
    icon: History,
    title: "AI-Powered Historical Data",
    description: "Let our AI find relevant historical data based on market sentiment, perfect for testing strategies in specific conditions.",
    link: "/historical-data"
  },
];

const workflowSteps = [
    {
        title: "Explore the Dashboard",
        description: "Get a high-level overview of your portfolio's performance, key metrics, and the latest AI signals.",
    },
    {
        title: "Develop a Strategy",
        description: "Use our backtesting engine to test different trading strategies, like Moving Average Crossovers or RSI-based rules.",
    },
    {
        title: "Get AI Suggestions",
        description: "Our AI analyzes your backtest results and suggests concrete features to improve your strategy's profitability and risk management.",
    },
    {
        title: "Paper Trade Your Strategy",
        description: "Implement your refined strategy in our paper trading environment to see how it performs in a simulated, live market.",
    },
     {
        title: "Stay Informed",
        description: "Use the Sentiment and AI Signal pages to gauge market mood and get real-time, data-driven trading ideas from our AI.",
    },
]

const jargon = [
    {
        term: "Backtesting",
        definition: "The process of testing a trading strategy on historical data to see how it would have performed in the past. It helps evaluate a strategy's viability without risking real money."
    },
     {
        term: "Paper Trading",
        definition: "Simulated trading that allows you to practice buying and selling securities without any real money involved. It's a safe way to learn the ropes."
    },
    {
        term: "Sentiment Analysis",
        definition: "The use of Natural Language Processing (NLP) to analyze text (like news articles or social media) to determine if the underlying opinion is positive, negative, or neutral."
    },
    {
        term: "ROI (Return on Investment)",
        definition: "A performance measure used to evaluate the efficiency of an investment. It measures the amount of return on an investment relative to its cost."
    },
     {
        term: "Drawdown",
        definition: "The peak-to-trough decline during a specific period for an investment. It's a measure of downside risk."
    },
     {
        term: "Whipsaw",
        definition: "A condition where a security's price heads in one direction, but is then quickly followed by a movement in the opposite direction. These can lead to trading losses."
    }
]

export default function AboutPage() {
  return (
    <DashboardLayout>
      <div className="space-y-16 py-8">
        <header className="text-center space-y-4">
          <h1 className="text-5xl font-bold tracking-tighter bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60">
            Welcome to FinSim
          </h1>
          <p className="text-xl max-w-3xl mx-auto text-muted-foreground">
            Revolutionizing the trading landscape by making sophisticated
            financial tools accessible to everyone.
          </p>
        </header>

        <section className="grid md:grid-cols-3 gap-8 text-center">
          <Card className="transition-all hover:shadow-xl hover:-translate-y-1">
            <CardHeader>
              <div className="p-4 bg-primary/10 rounded-full w-fit mx-auto mb-4">
                <Target className="h-8 w-8 text-primary" />
              </div>
              <CardTitle>The Problem</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                The world of advanced trading has been gated by high costs,
                complex data, and a steep learning curve, leaving retail traders
                at a significant disadvantage.
              </p>
            </CardContent>
          </Card>
          <Card className="transition-all hover:shadow-xl hover:-translate-y-1">
            <CardHeader>
              <div className="p-4 bg-primary/10 rounded-full w-fit mx-auto mb-4">
                <Rocket className="h-8 w-8 text-primary" />
              </div>
              <CardTitle>Our Mission</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                To democratize algorithmic trading by providing powerful, AI-driven
                tools that are intuitive and educational, empowering you to build
                and test strategies with confidence.
              </p>
            </CardContent>
          </Card>
          <Card className="transition-all hover:shadow-xl hover:-translate-y-1">
            <CardHeader>
              <div className="p-4 bg-primary/10 rounded-full w-fit mx-auto mb-4">
                <Briefcase className="h-8 w-8 text-primary" />
              </div>
              <CardTitle>Our Solution</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground">
                FinSim is an AI-powered platform that simplifies market analysis,
                offers actionable insights, and provides a risk-free paper
                trading environment to hone your skills.
              </p>
            </CardContent>
          </Card>
        </section>

        <section className="space-y-8">
          <div className="text-center">
              <h2 className="text-3xl font-bold tracking-tight">Key Features</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                  Everything you need to go from idea to implementation in the world of algorithmic trading.
              </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature) => (
              <Link href={feature.link} key={feature.title}>
                  <Card className="flex flex-col transition-all hover:shadow-xl hover:-translate-y-1 h-full group">
                    <CardHeader className="flex-row gap-4 items-center">
                      <div className="p-3 bg-primary/10 rounded-full">
                          <feature.icon className="h-6 w-6 text-primary" />
                      </div>
                      <CardTitle className="text-xl">{feature.title}</CardTitle>
                    </CardHeader>
                    <CardContent className="flex-grow">
                      <p className="text-muted-foreground">{feature.description}</p>
                    </CardContent>
                    <CardFooter>
                          <div className="flex items-center text-primary font-medium">
                              Try It Now
                              <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" />
                          </div>
                    </CardFooter>
                  </Card>
              </Link>
            ))}
          </div>
        </section>

        <section className="space-y-12">
          <div className="text-center">
              <h2 className="text-3xl font-bold tracking-tight">How It Works: An End-to-End Workflow</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                  Follow this simple workflow to get the most out of FinSim and start building your own AI-powered trading strategies.
              </p>
          </div>
          <div className="relative">
              <div className="absolute left-1/2 top-0 h-full w-px bg-border -translate-x-1/2" aria-hidden="true"></div>
              <div className="space-y-12">
                  {workflowSteps.map((step, index) => (
                      <div key={index} className="relative flex items-center">
                          <div className="w-1/2 pr-8 text-right">
                            {index % 2 === 0 && (
                                  <Card className="transition-all hover:shadow-xl hover:scale-105">
                                      <CardHeader>
                                          <CardTitle>{step.title}</CardTitle>
                                          <CardDescription>{step.description}</CardDescription>
                                      </CardHeader>
                                  </Card>
                            )}
                          </div>
                          <div className="absolute left-1/2 -translate-x-1/2 bg-background p-2 rounded-full border-2 border-primary">
                              <span className="text-primary font-bold">{index + 1}</span>
                          </div>
                          <div className="w-1/2 pl-8">
                            {index % 2 !== 0 && (
                                  <Card className="transition-all hover:shadow-xl hover:scale-105">
                                      <CardHeader>
                                          <CardTitle>{step.title}</CardTitle>
                                          <CardDescription>{step.description}</CardDescription>
                                      </CardHeader>
                                  </Card>
                            )}
                          </div>
                      </div>
                  ))}
              </div>
          </div>
        </section>

        <section className="space-y-8">
          <div className="text-center">
              <h2 className="text-3xl font-bold tracking-tight">Why FinSim?</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                  Here's what sets us apart and why you should invest your time here.
              </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              <Card>
                  <CardHeader>
                      <Lightbulb className="h-8 w-8 text-primary mb-2"/>
                      <CardTitle>Strength: AI at the Core</CardTitle>
                  </CardHeader>
                  <CardContent>
                      <p className="text-muted-foreground">Unlike other platforms where AI is an afterthought, FinSim is built from the ground up with AI. From signal generation to strategy improvement, AI is your collaborative partner, not just a feature.</p>
                  </CardContent>
              </Card>
              <Card>
                  <CardHeader>
                      <CheckCircle className="h-8 w-8 text-green-500 mb-2"/>
                      <CardTitle>Benefit: Actionable Insights</CardTitle>
                  </CardHeader>
                  <CardContent>
                      <p className="text-muted-foreground">We don't just give you data; we give you explainable insights. Our "Explainable AI (XAI)" tells you *why* a signal was generated, helping you learn and build trust in the system.</p>
                  </CardContent>
              </Card>
              <Card>
                  <CardHeader>
                      <Scale className="h-8 w-8 text-yellow-500 mb-2"/>
                      <CardTitle>Drawback: A Simulated World</CardTitle>
                  </CardHeader>
                  <CardContent>
                      <p className="text-muted-foreground">FinSim is a powerful simulator, but it's not a live brokerage. Real-world trading involves factors like slippage and liquidity that aren't fully replicated here. Use FinSim to learn and test, then apply your knowledge cautiously in the real market.</p>
                  </CardContent>
              </Card>
          </div>
        </section>

        <section className="space-y-8">
          <div className="text-center">
              <h2 className="text-3xl font-bold tracking-tight">Decoding the Jargon</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                  We believe in making finance accessible. Here are some common terms you'll encounter, explained simply.
              </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {jargon.map(item => (
                  <div key={item.term} className="p-4 border rounded-lg bg-card">
                      <h4 className="font-bold text-primary">{item.term}</h4>
                      <p className="text-sm text-muted-foreground">{item.definition}</p>
                  </div>
              ))}
          </div>
        </section>

        <section className="space-y-8">
          <div className="text-center">
            <h2 className="text-3xl font-bold tracking-tight">Meet the Team</h2>
            <p className="text-muted-foreground">The minds behind the mission.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {teamMembers.map((member) => (
              <Card
                key={member.name}
                className="text-center transition-all hover:shadow-xl hover:-translate-y-1"
              >
                <CardContent className="pt-6">
                  <Avatar className="w-32 h-32 mx-auto mb-4 border-4 border-primary/10">
                    <Image
                      src={member.avatar}
                      alt={member.name}
                      width={128}
                      height={128}
                      data-ai-hint={member.aiHint}
                    />
                  </Avatar>
                  <h3 className="text-xl font-bold">{member.name}</h3>
                  <p className="text-primary font-medium">{member.role}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      </div>
    </DashboardLayout>
  );
}
