
"use client";

import { useState } from 'react';
import DashboardLayout from "@/components/dashboard/dashboard-layout";
import { AiSignalCard } from "@/components/dashboard/ai-signal-card";
import { AiSignalsTour } from "@/components/dashboard/ai-signals-tour";

const stocks = ["AAPL", "GOOGL", "TSLA", "MSFT", "NVDA", "AMZN"];

export default function AiSignalsPage() {
  const [isTourOpen, setIsTourOpen] = useState(true);

  return (
    <DashboardLayout>
       {isTourOpen && <AiSignalsTour onComplete={() => setIsTourOpen(false)} />}
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">
            AI-Driven Trading Signals
          </h1>
          <p className="text-muted-foreground">
            Actionable buy, sell, or hold signals generated by our AI models.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-8">
          {stocks.map((stock, index) => (
            <AiSignalCard key={stock} ticker={stock} isFirst={index === 0} />
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
}
